### ISSUE TITLE
for the datasets

### ISSUE THREAD

**Issue by chinure** [hezht3/CLHLS_diet_timedependent#1]
could you please provide the datasets you used

**Comment by hezht3** [comment]
You can apply access to the survey data at [Peking University Open Research Data Platform](https://opendata.pku.edu.cn/).

**Comment by chinure** [comment]
I am very appreciated for your reply, thx



At 2022-03-14 21:29:33, "Zhengting Johnathan He" ***@***.***> wrote:

You can apply access to the survey data at Peking University Open Research Data Platform.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
